[package]
name = "wasm"
version = "0.1.0"
edition = "2024"
authors = ["Thang X. Vu <thang@dedot.dev>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.104"
serde-wasm-bindgen = "0.6.5"
smoldot = { version = "0.20.0", default-features = false, git = "https://github.com/smol-dot/smoldot" }
parity-scale-codec = { version = "3.7.5", default-features = false }

[dev-dependencies]
frame-metadata = "23.0.0"